apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /app1
            backend:
              service:
                name: app1
                port:
                  number: 80
          - pathType: Prefix
            path: /app2
            backend:
              service:
                name: app2
                port:
                  number: 80
          - pathType: Prefix
            path: /app3
            backend:
              service:
                name: app3
                port:
                  number: 80
          - pathType: Prefix
            path: /app4
            backend:
              service:
                name: app4
                port:
                  number: 80