apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4
        image: app4-html:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80